using System.Globalization;
using System.IO;
using System.Xml;
using System.Xml.Serialization;

namespace EsccWebTeam.Data.Xml
{
    /// <summary>
    /// Utility class for working with web services
    /// </summary>
    /// <typeparam name="DataObjectType">The original <see cref="System.Type"/> of the data object returned by the web service.</typeparam>
    /// <typeparam name="ProxyObjectType">The <see cref="System.Type"/> of the object returned by the web service proxy</typeparam>
    public class WebServiceHelper<DataObjectType, ProxyObjectType>
    {
        private string webServiceNamespace;
        private string dataObjectXmlNamespace;

        /// <summary>
        /// Initializes a new instance of the <see cref="WebServiceHelper&lt;ProxyObjectType, DataObjectType&gt;"/> class.
        /// </summary>
        /// <param name="webServiceNamespace">The web service namespace.</param>
        /// <param name="dataObjectXmlNamespace">The data object's XML namespace.</param>
        /// <remarks>
        /// <para>Your web method returns an object of type "MyNamespace.MyType". When you call the web method from another project, the type
        /// you get back is one generated by the proxy, "WebReferenceNamespace.MyType". If you need to use some logic contained within
        /// "MyNamespace.MyType", it's not available. If you need to pass the object to a method which expects an instance of
        /// "MyNamespace.MyType", you can't. But if you pass your instance of "WebReferenceNamespace.MyType" to <see cref="ConvertProxyToOriginalType"/>
        /// you can turn it into an instance of "MyNamespace.MyType" which you <b>can</b> use.</para>
        /// <para>It's more complicated when the original type specifies an XML namespace for use when serialised. In that case the same namespace
        /// must be present in the XML root element in order to deserialise it to the original type. However, a web service proxy object puts the root
        /// element of the proxy type in the web service's own namespace. There are three possible solutions:</para>
        /// <list type="bullet">
        /// <item>Use the same namespace for the web service as for the type being returned (which may not be appropriate)</item>
        /// <item>Return the namespaced object inside some other container object, such as a collection (fine if you can alter the web service)</item>
        /// <item>Replace the namespace before deserialising the XML (implemented using the dataObjectXmlNamespace parameter of this class)</item>
        /// </list>
        /// </remarks>
        public WebServiceHelper(string webServiceNamespace, string dataObjectXmlNamespace)
        {
            this.webServiceNamespace = webServiceNamespace;
            this.dataObjectXmlNamespace = dataObjectXmlNamespace;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebServiceHelper&lt;DataObjectType, ProxyObjectType&gt;"/> class.
        /// </summary>
        /// <param name="webServiceNamespace">The web service namespace.</param>
        public WebServiceHelper(string webServiceNamespace)
        {
            this.webServiceNamespace = webServiceNamespace;
        }

        /// <summary>
        /// Converts a proxy object returned by a web service to its original type
        /// </summary>
        /// <param name="proxyObject">The proxy object</param>
        /// <returns>An instance of the original type, reserialised from the data contained in the proxy</returns>
        /// <example>
        /// <code>
        /// using EsccWebTeam.Events.Common;
        /// using EsccWebTeam.Data.Xml;
        /// 
        /// // call the web service and get back a proxy event
        /// EventCalendarWS.EventItem proxyEvent = EventCalendarWS.ExampleWebMethod(); 
        ///             
        /// // create an instance of a helper class which can convert it
        /// WebServiceHelper&lt;EsccWebTeam.Events.Common.EventItem, EventCalendarWS.EventItem&gt; proxyHelper = new WebServiceHelper&lt;EsccWebTeam.Events.Common.EventItem, EventCalendarWS.EventItem&gt;("http://czoneapps.eastsussex.gov.uk/Czone.WebService.EventCalendar/", typeof(EsccWebTeam.Events.Common.EventItem), typeof(EventCalendarWS.EventItem));
        /// 
        /// // convert the proxy event into a real event
        /// EsccWebTeam.Events.Common.EventItem convertedEvent = proxyHelper.ConvertProxyToOriginalType(proxyEvent);
        /// </code>
        /// </example>
        /// <seealso cref="ConvertOriginalTypeToProxy"/>
        public DataObjectType ConvertProxyToOriginalType(ProxyObjectType proxyObject)
        {
            XmlSerializer ser1 = new XmlSerializer(typeof(ProxyObjectType), this.webServiceNamespace);
            XmlSerializer ser2 = new XmlSerializer(typeof(DataObjectType), this.webServiceNamespace);
            string xml;

            // Serialize the webservice object to XML
            using (TextWriter textWriter = new StringWriter(CultureInfo.CurrentCulture))
            {
                ser1.Serialize(textWriter, proxyObject);
                xml = textWriter.ToString();
                textWriter.Close();
            }

            // If necessary, replace the web service namespace before rehydrating
            if (this.dataObjectXmlNamespace != null)
            {
                XmlDocument dom = new XmlDocument();
                dom.LoadXml(xml);
                if (dom.DocumentElement.NamespaceURI == this.webServiceNamespace)
                {
                    dom.DocumentElement.Attributes["xmlns"].Value = this.dataObjectXmlNamespace;
                    xml = dom.OuterXml;
                }
            }

            // Deserialize the XML to the original type
            XmlTextReader xmlReader = new XmlTextReader(new StringReader(xml));
            DataObjectType dataObject = (DataObjectType)ser2.Deserialize(xmlReader);
            xmlReader.Close();

            return dataObject;
        }

        /// <summary>
        /// Converts an original type to its web service proxy representation.
        /// </summary>
        /// <param name="dataObject">The data object.</param>
        /// <returns>Web service proxy object</returns>
        /// <seealso cref="ConvertProxyToOriginalType"/>
        public ProxyObjectType ConvertOriginalTypeToProxy(DataObjectType dataObject)
        {
            XmlSerializer ser1 = new XmlSerializer(typeof(DataObjectType), this.webServiceNamespace);
            XmlSerializer ser2 = new XmlSerializer(typeof(ProxyObjectType), this.webServiceNamespace);
            string xml;

            // Serialize the webservice object to XML
            using (TextWriter textWriter = new StringWriter(CultureInfo.CurrentCulture))
            {
                ser1.Serialize(textWriter, dataObject);
                xml = textWriter.ToString();
                textWriter.Close();
            }

            // If necessary, replace the data object namespace before rehydrating
            if (this.dataObjectXmlNamespace != null)
            {
                XmlDocument dom = new XmlDocument();
                dom.LoadXml(xml);
                if (dom.DocumentElement.NamespaceURI == this.dataObjectXmlNamespace)
                {
                    dom.DocumentElement.Attributes["xmlns"].Value = this.webServiceNamespace;
                    xml = dom.OuterXml;
                }
            }

            // Deserialize the XML to the original type
            XmlTextReader xmlReader = new XmlTextReader(new StringReader(xml));
            ProxyObjectType proxyObject = (ProxyObjectType)ser2.Deserialize(xmlReader);
            xmlReader.Close();

            return proxyObject;
        }
    }

}
